### ISSUE TITLE
Update readme to include instructions for restricted access permission on Android 13+

### ISSUE THREAD

**Issue by Dave247** [DreadedLama/dnd-sync#2]
It was already mentioned by someone in a issue on the original source repo [here](https://github.com/rhaeus/dnd-sync/issues/7), which is what I also had to do to get the app properly working on my Pixel 7 Pro which runes Android 14.

**Comment by DreadedLama** [comment]
The readme is already updated, there is a NOTE section at the end regarding the same. But I'll move it above so that it is in sync with other steps.

**Comment by Dave247** [comment]
Oh so it was, my apologies I totally overlooked that. It's probably better to put it under the Phone steps subheading though yeah, as that's where I looked originally and didn't notice any changes from what I remembered.

**Comment by DreadedLama** [comment]
Yes, that makes sense. Will make the required changes in readme.
