### ISSUE TITLE
Bedtime mode not being synced between Galaxy Watch 4 and NP1

### ISSUE THREAD

**Issue by Silleellie** [DreadedLama/dnd-sync#3]
Hello and thank you for the great fork! The app sounds amazing, but sadly only DND is being synced between the watch and the phone. I know that it is a 1-way sync, but from the phone I tried starting bedtime mode both manually and automatically when charger is plugged in, but again only DND is being synced.

The Nothing Phone 1 has pretty stock firmware so I expected this to work without any issues, since this has been tested with a pixel phone, but I had no luck :(

All permissions are granted both on the phone and the watch. If I can send you some useful info for debugging please tell me!

Thank you in advance 🤗

**Comment by Silleellie** [comment]
It turns out that the fork by @DreadedLama only supports bedtime mode if the language of the phone is set to **"english"**. I forked its repo and solved this issue by myself!

Check it out! [Repo link](https://github.com/Silleellie/dnd-bedtime-sync)

**Comment by DreadedLama** [comment]
Yes, it only supports the English language as of now, will add all language support soon. As I was on a personal break, did not get time to look into this.
Also, great work implementing it in your fork.
